"""Adding new column to force migration

Revision ID: 280684d8a467
Revises: 
Create Date: 2024-10-26 20:06:59.259442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280684d8a467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=True))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')

    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
