"""removing new columns

Revision ID: 63cbc64a7d37
Revises: 280684d8a467
Create Date: 2024-10-26 20:08:16.241705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cbc64a7d37'
down_revision = '280684d8a467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
