"""fixed typo

Revision ID: 93cb2673ced3
Revises: 901a96e7bbc8
Create Date: 2024-10-26 23:32:00.965604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cb2673ced3'
down_revision = '901a96e7bbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
