"""removed stuff

Revision ID: 9e7df077ad78
Revises: 
Create Date: 2024-10-26 23:21:01.384757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7df077ad78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_column('empty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empty', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
